### PR TITLE
Python Worker Server-Side Middleware

### PR DESCRIPTION
**Pull request by chelhuff**
The company I'm interning with needed middleware functionality similar to that found in the faktory ruby worker but for the python jobs their applications runs, and needed it to be simple enough to not cause any ripples through the preexisting codebase. This is a simple addition that I coded for them that allows all middleware to be created and managed from worker.py. Hopefully this is helpful, but any feedback would also be greatly appreciated.

### CODE REVIEW

**Comment by mperham** [comment]
You might consider the two places for middleware: on job push and on job execution.  Sidekiq calls this client and server middleware, e.g.

https://github.com/mperham/sidekiq/wiki/Middleware

Calling your implementation "middleware" is ambiguous about which case it solves.

**Comment by cdrx** [comment]
Thanks for submitting this. I'm snowed under with work at the moment so not had a chance to review wit properly, but a couple of notes from a quick look over the code:

- with the middleware functions stored in a `dict`, they will not be applied in a deterministic order. Can you use an OrderedDict or a list for this?
- is there an ability for a middleware function to either cancel the job, or mutate the arguments that are sent to faktory?

**Comment by chelhuff** [comment]
@cdrx an engineer on my team just pointed out the issue with plain dictionaries, so I'm changing that right now and I'm also working on a way for the middleware to play a greater role in how jobs can be executed. I just want to make sure I fully understand everything the code is currently doing before I change things that should be left as they are.

**Comment by chelhuff** [comment]
@cdrx  @mperham I've added the ability to mutate/kill workers and call middleware after a job has been executed. mutation/killing is all done based on the return value a middleware function.

**Comment by chelhuff** [comment]
@gowabash I've implemented the changes you've suggested and @mperham i'm curious about what you mean by "executing around". Currently client middleware is called -> the job is submitted to be processed -> the job either succeeds or fails -> server middleware is called. I understand that all of this should be considered server middleware, but I don't think I understand the difference between it calling before and after, or running around execution.

**Comment by mperham** [comment]
Say you want to set a global User associated with the job that's going to execute.  The client middleware would save any global user_id into the job payload before pushing it to the server.  The worker middleware allows you to restore that User context while the job is executing, like this:

```ruby
  def call(worker, job, queue)
    # 1. Set the User global
    User.current_id = job[‘user_id’]

    # 2. execute the job
    yield 

  ensure
    # 3. Unset the global
    User.current_id = nil
  end
```

`yield` is where the job is executed so steps 1 and 3 "wrap around" the yield.

**Comment by mperham** [comment]
See also https://drivy.engineering/use-sidekiq-middleware/

**Comment by mperham** [comment]
As a side note, by "global" I mean "thread local".  I don't know if FWP is multi-threaded but it's a good idea to make the code thread-safe if possible.

**Comment by chelhuff** [comment]
Awesome, I've been working on it and have something that looks like this:
`def someServerMiddleware(worker, job, iterator):

    #do some stuff before execution

    try:#attempt to run next middleware function
        middlewareChain = next(iterator)
        middlewareChain(worker, job, iterator)
    #if no functions remain, execute the job
    except StopIteration:
        worker.process(job)

    #do more stuff after execution
`
python doesn't really have a `yield` equivalent so instead I'm nesting function calls to registered middleware, and once the job processes, the stack unwinds through every function previously called

`def someMiddleware(worker, job):

    #do some stuff before execution
    worker.chain_middleware(worker, job)#execute the job
    #do more stuff after execution
` 
I'm also considering wrapping this inside of a worker method, so it can be implemented in a single line, but I'm not sure it's worth adding more function calls to the stack

**Comment by Envek** [comment]
It would be nice to have middlewares in faktory worker for Python. For example it is the most appropriate place to put various monitoring calls to. Any chance to ressurect this pull request?

**Comment by cdrx** [comment]
I'm closing this for now, because it hasn't been worked on for a while.

Happy to look at a rebased PR in the future if it is still something you need.

**Pull request closed without merging**
